### ISSUE TITLE
loads of repetition of a message

### ISSUE THREAD

**Issue by lkrnrw** [gluc/data.tree#166]
I am trying to have some data, which come in a data tree structure, accompany a package I am trying to wrap. Upon devtools::check(), the following message is displayed about 28000 times:

[1] "Node$fieldsAll will be deprecated in the next release. Please use Node$attributesAll instead."

I don't remember to have typed in the key stroke sequence "Node$fieldsAll" ever before writing this issue, so I guess the function must have been called internally when preparing the data for lazy loading. 

Also, the error message is issued:

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : there is no package called '<-'

Don't know if this is related but I am lost as to how to search for the offending bits in the code.

**Comment by Matherion** [comment]
I'm running into the same thing. What's worse, with newer versions of R the error seems to occur more frequently:

![image](https://github.com/gluc/data.tree/assets/2077242/86c47357-569c-42f9-abba-91c954c68a41)

This is starting to become more problematic now. I _did_ used to use the `$fields` and `#fieldsAll` properties, but have replaced all calls with calls to `$attributes` and `$attributesAll` now, and to no avail.

I therefore share the concern/'diagnosis' that this error results from an internal call to the deprecated properties.

This is an awesome package, as is also reflected in the downloads (>10K / month), so it would be really awesome if this could be fixed 🙂 @gluc, if I locally clone the package and submit a pull request, could you push the new version to CRAN (because my packages import `data.tree`, so a github-only version wouldn't cut it in my case)?

And if so, which branch should I pull? The `dev` branch?

**Comment by Matherion** [comment]
@brownag suggested a relatively quick fix in https://github.com/ncss-tech/interpretation-engine/issues/3 - I could implement that, but @gluc, I'd like to check whether this repo/package is still somewhat alive / maintained first 🙂

**Comment by gluc** [comment]
Will be fixed in the next release (due Nov 2023)

**Comment by jranke** [comment]
The commit did not really close the issue, that's why I filed the duplicate #173
