### ISSUE TITLE
Is there a library similar to data.tree for python?

### ISSUE THREAD

**Issue by vnijs** [gluc/data.tree#170]
@gluc I have have been using your data.tree package for quite some time now. Works great for decision analysis. I'm doing more work with python and shiny for python these days and was wondering if you were aware of any libraries in python that have similar functionality to data.tree. The closest I found so far was `nutree`. 

https://github.com/mar10/nutree

**Comment by gluc** [comment]
Hey Vincent, thx! Indeed, I have also been working more in py recently. This is also the reason why I haven't bee super active on data.tree anymore. Though I do plan to publish un update later this year.
Anyway, to your question: No, I'm not aware of any other package in python. I guess the reason is that OO is built-in, so building tree-structures from scratch is simpler. nutree looks very similar in scope indeed, but I've never used it. Do let me know if you find a viable alternative!

**Comment by gluc** [comment]
Closing

**Comment by lverweijen** [comment]
If you’re looking for something similar in Python, you might try [littletree](https://github.com/lverweijen/littletree). I built it because I wasn’t fully satisfied with the popular options: AnyTree is intuitive but can be slow, while itertree is fast but less simple to use. Littletree aims for a balance between speed and simplicity.

Here is an example recreating `CreateRegularTree` from **data.tree**:
```python
from littletree import Node

def regular_tree(height=5, branching_factor=6):
    """Create a regular tree."""
    root = Node()
    _regular_tree(height, branching_factor, root)
    return root

def _regular_tree(height, branching_factor, parent):
    if height:
        for i in range(branching_factor):
            child = Node(identifier=i)
            parent.add_child(child, check_loop=False)
            _regular_tree(height - 1, branching_factor, child)

tree = regular_tree()
```
On my laptop this runs in about 0.006 seconds.

If you try it, let me know what you think. Here is the [documentation](https://lverweijen.github.io/littletree/).
