### ISSUE TITLE
Install package problem

### ISSUE THREAD

**Issue by sherrylau** [gluc/data.tree#38]
Hi 

I am trying to install the package with devtools::install_github("gluc/data.tree") but i got this error:

* installing *source* package ‘data.tree’ ...
** package ‘data.tree’ successfully unpacked and MD5 sums checked
** R
** data
** inst
** preparing package for lazy loading
Error in R6Class("Node", lock_objects = FALSE, public = list(parent = NULL,  : 
  unused argument (lock_objects = FALSE)
Error : unable to load R code in package ‘data.tree’
ERROR: lazy loading failed for package ‘data.tree’

Can you help me to resolve this?

Thanks,
Sherry

**Comment by gluc** [comment]
Yes, I can reproduce, and the problem seems to be a corrupt version of R6 on github. The remedy is to install R6 from CRAN.

Pls do the following:
1. uninstall the packages R6 and data.tree (e.g. from RStudio, or using something like `remove.packages("R6", lib="~/R/win-library/3.2")`
2. install R6 from CRAN: `install.packages("R6")`
3. install data.tree from github: `devtools::install_github("gluc/data.tree")`

Side note: the github master branch of data.tree is equivalent to CRAN. So you might also do `install.packages("data.tree")` from the beginning. This would take care of the dependencies.

Let me know if that doesn't help.

**Comment by sherrylau** [comment]
It works for me. Thanks for your help!

Sherry
