### ISSUE TITLE
Does node work with multidimensional array

### ISSUE THREAD

**Issue by glennmschultz** [gluc/data.tree#56]
Hi Christoph,

The function works in the waterfall logic.  However, the call to node$CashFlow[] does work with a matrix.  Does node$ only work with a matrix?

Pmt_Period <- function(node, period = numeric(), CashFlowTable = "character"){
Deal$`1AH`$CashFlow[period, "Period"] = as.numeric(CashFlowTable[period, "Period"])
Deal$`1M1`$CashFlow[period, "Period"] = as.numeric(CashFlowTable[period, "Period"])
Deal$`1M1H`$CashFlow[period, "Period"] = as.numeric(CashFlowTable[period, "Period"])
Deal$`1M2`$CashFlow[period, "Period"] = as.numeric(CashFlowTable[period, "Period"])
Deal$`1M2H`$CashFlow[period, "Period"] = as.numeric(CashFlowTable[period, "Period"])
Deal$`1B1H`$CashFlow[period, "Period"] = as.numeric(CashFlowTable[period, "Period"])
}

while this function produces the error below

Pmt_Period <- function(node, period = numeric(), CashFlowTable = "character"){
node$CashFlow[period, "Period"] = as.numeric(CashFlowTable[period, "Period"])
}

Error in node$CashFlow[period, "Period"] = as.numeric(CashFlowTable[period, : 
incorrect number of subscripts on matrix

**Comment by gluc** [comment]
Hi Glenn,

That's hard to say from your example, but my first guess would be that it's
not data.tree related. In any case there's nothing I know of that would
inhibit it to work with matrices. For an example, see below. Otherwise, I'm
afraid you need to send me a reproducable example.

Best, c.

> data(acme)> acme$IT$CashFlow <- matrix(0, 2, 2)> acme$IT$CashFlow[1,2] <- 5> acme$IT$CashFlow     [,1] [,2]
[1,]    0    5
[2,]    0    0




Glenn Schultz <notifications@github.com> schrieb am So., 14. Feb. 2016 um
00:03 Uhr:

**Comment by gluc** [comment]
Closing, as this seems to have been resolved.
