### ISSUE TITLE
ToDataFrameTree does not perform well for large data sets

### ISSUE THREAD

**Issue by kickbox** [gluc/data.tree#74]
ToDataFrameTree takes more time to generate data frme from data.tree. Need to optimise for performance

**Comment by gluc** [comment]
@kickbox see comment in #73

**Comment by gluc** [comment]
I committed a change to dev. It should improve the performance by a factor 4.  The problem was the formatting, which was turned on by default. So, for every node, the entire ancestor path was search for a formatter. Now, formatting is turned off by default.
You can try it out from the dev branch:
```
devtools::install_github("gluc/data.tree", ref = "dev")
```
The issue will be closed when this is released.
I realise that this is still far from performance on non-hierarchical data sets. However, with the current design/technology I'm afraid there will be no miracles. The reason is that each Node is an R6 object. But please do let me know if you have an idea. Happy to accept pull requests and be proven otherwise ;-)

**Comment by kickbox** [comment]
Thank you @gluc. It now takes 12 seconds and 5 seconds respectively. This is indeed a major performance improvement. You can close the issue. However I will accept your challenge and work on it soon :)
